mnemonic: ${EL_AND_CL_MNEMONIC}
el_premine:
  "m/44'/60'/0'/0/0": 1000000000ETH
  "m/44'/60'/0'/0/1": 1000000000ETH
  "m/44'/60'/0'/0/2": 1000000000ETH
el_premine_addrs: ${EL_PREMINE_ADDRS}
additional_preloaded_contracts: ${ADDITIONAL_PRELOADED_CONTRACTS}
